name: Nginx-stable

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '22 7 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  


jobs:
  version:
    name: Get NGINX stable version
    runs-on: ubuntu-22.04
    outputs:
      major: ${{ steps.version.outputs.major }}
      minor: ${{ steps.version.outputs.minor }}
      patch: ${{ steps.version.outputs.patch }}
      custom_date: ${{ steps.version.outputs.CUSTOM_DATE }}
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        
      - name: Parse NGINX stable version
        id: version
        run: |
          echo "major=1" >> "$GITHUB_OUTPUT"
          echo "minor=22" >> "$GITHUB_OUTPUT"
          echo "patch=1" >> "$GITHUB_OUTPUT"
          echo "CUSTOM_DATE=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT
      
  build:
    name: Build NGINX stable version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: [version]  
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2


      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image x86_64
        id: build-and-push-x86_64
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: "{{ defaultContext }}:x86_64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/reli4ble/nginx-minimal-unprivileged-x86_64:${{ needs.version.outputs.major }}.${{ needs.version.outputs.minor }}.${{ needs.version.outputs.patch }}_${{ needs.version.outputs.custom_date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build and push Docker image aarch64
        id: build-and-push-aarch64
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: "{{ defaultContext }}:aarch64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/reli4ble/nginx-minimal-unprivileged-aarch64:${{ needs.version.outputs.major }}.${{ needs.version.outputs.minor }}.${{ needs.version.outputs.patch }}_${{ needs.version.outputs.custom_date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max    


      
